apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-data
  namespace: portfolio-pvc-demo
spec:
  accessModes:
    - ReadWriteOnce
  # storageClassName: gp3     # (descomenta si la default no es EBS)
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: portfolio-pvc-demo
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:6.3
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql
            - name: WORDPRESS_DB_USER
              value: root
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root
                  key: password
            - name: WORDPRESS_DB_NAME
              value: wordpress
          volumeMounts:
            - name: wp-data
              mountPath: /var/www/html
      volumes:
        - name: wp-data
          persistentVolumeClaim:
            claimName: wp-data
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: portfolio-pvc-demo
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
    - port: 80
      targetPort: 80
